### ISSUE TITLE
Breaks when trying to open a lot of notifications quickly

### ISSUE THREAD

**Issue by adam-lynch** [edjafarov/node-webkit-desktop-notification#6]
Just using the example app, I clicked a notification link a lot quickly then I got this uncaught error:

```
Error: Unable to get render view in GetWindowObject
    at Error (native)
    at Window.window (window_bindings.js:166:10)
    at getFreeWin (app://node-webkit-desktop-notification/desktopNotification.js:536:31)
    at new DesktopNotification (app://node-webkit-desktop-notification/desktopNotification.js:567:14)
    at showFunnyNotification (app://node-webkit-desktop-notification/index.html:71:17)
    at HTMLAnchorElement.onclick (app://node-webkit-desktop-notification/index.html:24:141)
```

**Comment by adam-lynch** [comment]
This was on Windows 8.1 by the way. Also, I do have node-webkit@0.10.5 installed globally but you build for 0.10.3, just in case that could be related but I doubt it.

**Comment by TimApplepie** [comment]
I get this error when I have more than 7 open notifications. 
I think this is caused because you create (only) 6 empty notification windows:

``` javascript
for(var w= 0;w < 6;w++){
        var winOpen = gui.Window.open(desktopNotificationHtml, defaultOptions);
        ...
}
```

**Comment by netconstructor** [comment]
Can anyone confirm that changing the value higher results in a temp fix?

**Comment by emarten** [comment]
Yes and No.. It works, but it blows up the memory-usage. `javascript function getFreeWin() {}` creates the Window, but it never seems to be loaded/ready.
